name: Publish to Github Pages

on:
  pull_request:
    types:
      - closed
    tags:
      - 'v*'
    branches:
      - master

jobs:
    gh-pages:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]

      steps:
        - uses: actions/checkout@v2
        - name: Install node
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm i
        - run: npm run build
        - name: Deploy to Github Pages
          uses: JamesIves/github-pages-deploy-action@4.1.4
          with:
            branch: gh-pages
            folder: build

    docker:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v2
        - name: set up qemu
          uses: docker/setup-qemu-action@v1
        - name: set up buildx
          uses: docker/setup-buildx-action@v1
        - name: log in to ghcr
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: mathisburger
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: build and push
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: ghcr.io/mathisburger/mathonweb:latest

    release:
      if: github.event.pull_request.merged == true
      name: publish release
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: create Release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: latest
            release_name: latest
            body: |
              Changes in this Release:
              - Checkout <a href="https://mathonweb.mathis-burger.de">https://mathonweb.mathis-burger.de</a> to
                get the latest changelogs.
            draft: false
            prerelease: false
